name: Building and deploying

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . --tag ghcr.io/ashenoooone/duck-web:latest
        docker push ghcr.io/ashenoooone/duck-web:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}

        script: |
          docker login ghcr.io -u ashenoooone -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/ashenoooone/duck-web:latest
          docker stop duck-web || true
          docker rm duck-web || true 
          docker run \
           --name duck-web -p 80:80 \
           -d ghcr.io/ashenoooone/duck-web:latest 
